 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     docker:
       - image: zackads/hmrc-hr  
    
     steps:
       - checkout
       - setup_remote_docker:
          docker_layer_caching: true
       - run: dotnet build

