version: 2.1

orbs:
  heroku: circleci/heroku@1.2.3 # Invoke the Heroku orb
  docker: circleci/docker@1.5.0
  deploy-to-heroku: betterdoc/deploy-to-heroku@4.2.0
  newman: postman/newman@0.0.2

workflows:
    heroku_deploy:
      jobs:
        - build
        - newman-collection-run:
            requires:
              - build
        - deploy-dev:
            requires:
              - newman-collection-run
jobs:
  newman-collection-run:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./backend-tests/Test_Collections/Zing-Tech-Backend.postman_collection.json
          
  deploy-dev:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login 
            cd academy20-zingtech-backend
            pwd
            ls
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a zingtech-backend web
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a zingtech-backend web
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout
      # Bundle install dependencies
      - run:
          name: Restore packages
          command: 
            dotnet restore
      - run:
          name: Build App
          command: 
            dotnet build
      - run:
          name: Run Tests
          command: dotnet test
