 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     docker:
       - image: zackads/hmrc-hr  
    
     steps:
       - checkout
       - run:
           name: Restore
           command: dotnet restore
       - run: 
           name: Build
           command: dotnet build
       - setup_remote_docker:
          docker_layer_caching: true
       

