version: 2.1

orbs:
  heroku: circleci/heroku@1.2.3 # Invoke the Heroku orb
  docker: circleci/docker@1.5.0

workflows:
    heroku_deploy:
      jobs:
        - build
        - deploy: #heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
            requires:
              - build
        - heroku/push-docker-image
#          filters:
#            branches:
#              only: sequential-branch-filter

jobs:
  deploy:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - setup_remote_docker:
          version: 19.03.13
      
    
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
#    working_directory: ~/academy20-zingtech-backend/academy20-zingtech-backend
    steps:
      - checkout
      # Bundle install dependencies
      - run:
          name: Restore packages
          command: 
            dotnet restore
      - run:
          name: Build App
          command: 
            dotnet build
      - run:
          name: Run Tests
          command: dotnet test
#      - run:
#          name: Run app
#          command: 
#            dotnet run --project academy20-zingtech-backend
#  deploy-dev:
#    machine: true
#    steps:
#      - checkout
#      - run:
#          name: Build and push Docker image to Heroku
#          command: |
#            sudo curl https://cli-assets.heroku.com/install.sh | sh
#            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
#            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a academy20-zingtech-backend web
#            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a academy20-zingtech-backend web