version: 2.1

orbs:
  heroku: circleci/heroku@1.2.3 # Invoke the Heroku orb

workflows:
    heroku_deploy:
      jobs:
        - build
#        - push-docker-image: #heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
#            requires:
#              - build
#          filters:
#            branches:
#              only: sequential-branch-filter

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    working_directory: ~/academy20-zingtech-backend
    steps:
      - checkout
      # Bundle install dependencies
      - run:
          name: Restore packages
          command: 
            dotnet restore
      - run:
          name: Build App
          command: 
            dotnet build
      - run:
          name: Run app
          command: 
            dotnet run