version: 2.1

orbs:
  heroku: circleci/heroku@1.2.3 # Invoke the Heroku orb
  docker: circleci/docker@1.5.0
  deploy-to-heroku: betterdoc/deploy-to-heroku@4.2.0

workflows:
    heroku_deploy:
      jobs:
        - test
        - deploy:
            requires:
              - test
jobs:
  test:
    docker: 
      - image: cimg/node:15.2.0
    steps:
      - checkout
      - run:
          name: Start API + database containers
          command: |
            cd academy20-zingtech-backend
            docker-compose up -d
            docker-compose exec api dotnet dotnet-ef database update
      - run:
          name: Set up Newman for testing
          command: |
            npm install
      - run:
          name: Execute integration tests with Newman
          command: npm exec newman run backend-tests/integration/*.postman_collection.json
      - run:
          name: Bring down API and database containers
          command: docker-compose down
      - run: 
          name: Execute unit tests with NUnit
          command: |
            docker-compose exec api dotnet test
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login 
            cd academy20-zingtech-backend
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a zingtech-backend web 
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a zingtech-backend web