version: '3.1'

volumes:
  local_postgres_data: {}

services:
  api: 
    build:
      context: .
      target: build
    ports:
      - '8080:80'
    depends_on:
      - db
  
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: zing-back
      POSTGRES_PASSWORD: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data