version: '3.7'

services:
  api: 
    build:
      context: .
      target: build
    ports:
      - 8080:80
    depends_on:
      - db
  
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: zing-back
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432